# This workflow is for use in releasing this repo, and not meant for reuse elsewhere

name: Push workflow
on: push
jobs:
  release-it-workflow:
    # Use a local reference to the workflow file to use version defined by the repo state
    uses: ./.github/workflows/release-it-workflow.yaml
    with:
      app-id: 1049549 # release-it-gh-workflow release-it app
      app-environment: Repo release
    secrets:
      app-secret: ${{ secrets.RELEASE_IT_GITHUB_APP_KEY }} # Secret belonging to the Repo release environment
